[toolchain]

[features]
resolution = true
skip-lint = false
seeds = true

[programs.localnet]
counter = "7HVmH84UHpKxBjv5LNmGA4Mf4raJLuT3ixkLgy3Ks9zQ"

[programs.devnet]
counter = "7HVmH84UHpKxBjv5LNmGA4Mf4raJLuT3ixkLgy3Ks9zQ"



[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
